// <auto-generated />
using System;
using DFleet_CRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DFleetCRUD.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DFleet_CRUD.Models.Dominio.Abastecimento", b =>
                {
                    b.Property<int>("AbastecimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbastecimentoId"));

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CombustivelUtilizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletouTanque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAbastecimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estabelecimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frentista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QuantidadeLitros")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoAbastecimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorLitro")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Veiculo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbastecimentoId");

                    b.ToTable("Abastecimento");
                });
#pragma warning restore 612, 618
        }
    }
}
